package sleet;

public class SleetException extends Exception {

  /**
   * generated by eclipse
   */
  private static final long serialVersionUID = -404982431470350032L;

  public SleetException(String message, Throwable cause) {
    super(message, cause);
  }

  public SleetException(String message) {
    super(message);
  }

  public SleetException(Throwable cause) {
    super(cause);
  }

}
