package sleet.generators.time;

import sleet.generators.GeneratorException;

public class TimeDependencyException extends GeneratorException {
  /**
   * generated by eclipse
   */
  private static final long serialVersionUID = 6677540619792779318L;

  public TimeDependencyException(String message, Throwable cause) {
    super(message, cause);
  }

  public TimeDependencyException(String message) {
    super(message);
  }

  public TimeDependencyException(Throwable cause) {
    super(cause);
  }

}
