package sleet.generators.time;

import sleet.generators.GeneratorException;

public class TimeDependencyException extends GeneratorException {
  /**
   * generated by eclipse
   */
  private static final long serialVersionUID = 6677540619792779318L;

  public TimeDependencyException(String message, Throwable cause, boolean enableSuppression,
      boolean writableStackTrace) {
    super(message, cause, enableSuppression, writableStackTrace);
    // TODO Auto-generated constructor stub
  }

  public TimeDependencyException(String message, Throwable cause) {
    super(message, cause);
    // TODO Auto-generated constructor stub
  }

  public TimeDependencyException(String message) {
    super(message);
    // TODO Auto-generated constructor stub
  }

  public TimeDependencyException(Throwable cause) {
    super(cause);
    // TODO Auto-generated constructor stub
  }

}
