package sleet.generators;

import sleet.SleetException;

public class GeneratorException extends SleetException {
  /**
   * generated by eclipse
   */
  private static final long serialVersionUID = -2408099842630238442L;

  public GeneratorException(String message, Throwable cause) {
    super(message, cause);
  }

  public GeneratorException(String message) {
    super(message);
  }

  public GeneratorException(Throwable cause) {
    super(cause);
  }

}
