package sleet.generators;

public class GeneratorConfigException extends GeneratorException {
  /**
   * generated by eclipse
   */
  private static final long serialVersionUID = -2894157024668803650L;

  public GeneratorConfigException(String message, Throwable cause) {
    super(message, cause);
  }

  public GeneratorConfigException(String message) {
    super(message);
  }

  public GeneratorConfigException(Throwable cause) {
    super(cause);
  }

}
