package sleet.generators;

import sleet.SleetException;

public class GeneratorConfigException extends SleetException {
  /**
   * generated by eclipse
   */
  private static final long serialVersionUID = -2894157024668803650L;

  public GeneratorConfigException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
    super(message, cause, enableSuppression, writableStackTrace);
  }

  public GeneratorConfigException(String message, Throwable cause) {
    super(message, cause);
  }

  public GeneratorConfigException(String message) {
    super(message);
  }

  public GeneratorConfigException(Throwable cause) {
    super(cause);
  }

}
