package sleet.generators;

public class GeneratorSessionException extends GeneratorException {
  /**
   * generated by eclipse
   */

  private static final long serialVersionUID = -5663201042060915360L;

  public GeneratorSessionException(String message, Throwable cause) {
    super(message, cause);
  }

  public GeneratorSessionException(String message) {
    super(message);
  }

  public GeneratorSessionException(Throwable cause) {
    super(cause);
  }

}
