package sleet.generators;

import sleet.SleetException;

public class GeneratorException extends SleetException {
  /**
   * generated by eclipse
   */
  private static final long serialVersionUID = -2408099842630238442L;

  public GeneratorException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
    super(message, cause, enableSuppression, writableStackTrace);
    // TODO Auto-generated constructor stub
  }

  public GeneratorException(String message, Throwable cause) {
    super(message, cause);
    // TODO Auto-generated constructor stub
  }

  public GeneratorException(String message) {
    super(message);
    // TODO Auto-generated constructor stub
  }

  public GeneratorException(Throwable cause) {
    super(cause);
    // TODO Auto-generated constructor stub
  }

}
