package sleet.generators;

public class IdOverrunException extends GeneratorException {
  /**
   * generated by eclipse
   */
  private static final long serialVersionUID = 6754925706659214152L;

  public IdOverrunException(String message, Throwable cause) {
    super(message, cause);
  }

  public IdOverrunException(String message) {
    super(message);
  }

  public IdOverrunException(Throwable cause) {
    super(cause);
  }

}
