package sleet.generators;

public class IdOverflowException extends GeneratorException {
  /**
   * generated by eclipse
   */
  private static final long serialVersionUID = 6754925706659214152L;

  public IdOverflowException(String message, Throwable cause) {
    super(message, cause);
  }

  public IdOverflowException(String message) {
    super(message);
  }

  public IdOverflowException(Throwable cause) {
    super(cause);
  }

}
