package sleet.generators.reservedinstance;

import sleet.generators.GeneratorException;

public class ReservedInstanceTimeoutException extends GeneratorException {
  /**
   * generated by eclipse
   */

  private static final long serialVersionUID = -5663201042060915360L;

  public ReservedInstanceTimeoutException(String message, Throwable cause) {
    super(message, cause);
  }

  public ReservedInstanceTimeoutException(String message) {
    super(message);
  }

  public ReservedInstanceTimeoutException(Throwable cause) {
    super(cause);
  }

}
